name: run tests

on:
 push:
  branches: "main"

jobs:
 run-tests:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v4.1.2

   - name: Setup Java JDK
     uses: actions/setup-java@v4.2.1
     with: 
      java-version: '17'
      distribution: 'corretto'
      cache: maven

   - name: Setup Maven Action
     uses: s4u/setup-maven-action@6d44c18d67d9e1549907b8815efa5e4dada1801b
     with: 
       java-version: 17
       

   - name: Setup Chrome
     uses: browser-actions/setup-chrome@latest
   - run: chrome --version  




  
  
