name: run tests

on:
 push:
  branches: "main"

jobs:
 run-tests:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v4.1.2

   - name: Setup Java JDK
     uses: actions/setup-java@v4.2.1
     with: 
      java-version: '17'
      distribution: 'corretto'
      cache: maven
      
   - name: Setup Chrome
     uses: browser-actions/setup-chrome@v1.5.0
     
   - name: setup-chromedriver
     uses: nanasess/setup-chromedriver@v2.2.2
   
    

   - name: run tests
     run: mvn test
   
  
