name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Run-on-Chrome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven

    - name: Maven test
      run: mvn test
      env:
        ENV_BROWSER_NAME: "CHROME"
    - name: Attach screenshots and reports from Chrome
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots-and-report-Chrome
        path: |
          screenshots
          target/surefire-reports/emailable-report.html

  Run-on-FireFox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Maven test
        run: mvn test
        env:
          ENV_BROWSER_NAME: "FIREFOX"

          
      - name: Allure Report with history
        uses: simple-elf/allure-report-action@v1.9
        if: always()
        with:
            allure_results: target/allure-results
            allure_report: allure-report 
            gh_pages: gh-pages
            allure_history:  allure-history
            
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
    
    
    
   
          

