name: Run Tests

on:
  pull_request:
    branches:
      - master
      - issue-*
  push:
    branches:
      - master
      - issue-*

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -B

      - name: Test with Maven
        run: mvn test
