name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    container:
      image: selenium/standalone-chrome:latest

    env:
      CHROME_DRIVER_PATH: /usr/bin/google-chrome

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -B

      - name: Test with Maven
        run: mvn test
